### ISSUE TITLE
the option full screen is down

### ISSUE THREAD

**Issue by amatoSami3** [LZHD/ng-picture-viewer#1]
when i click on full screen icon the image does not displayed in full screen like demo project

**Comment by LZHD** [comment]
> 当我单击全屏图标时，图像无法像演示项目一样全屏显示

```
@import "~iv-viewer/dist/iv-viewer.min.css"
```

**Comment by amatoSami3** [comment]
@LZHD plz we can resize the component (width and height) because it is too small

**Comment by LZHD** [comment]
```
<nz-picture-viewer [images]="images" imgViewerClass="customize"></nz-picture-viewer>
```
### Template style
```
::ng-deep .customize {
  width: 800px !important;
  height: 800px !important;
}
```
or
### Global style
```
.customize {
  width: 800px !important;
  height: 800px !important;
}
```
@amatoSami3

**Comment by amatoSami3** [comment]
@LZHD  谢谢 
i use percentage instead of pixel  but the component does not display
